#apps += Uart::App
#app_headers += apps/uart/app.h

#app_code_src = $(addprefix apps/uart/,\
#  app.cpp \
#  main_controller.cpp \
#  monitor_controller.cpp \
#)

#app_code_src += $(app_code_test_src)
#apps_src += $(app_code_src)

#i18n_files += $(addprefix apps/uart/,\
#  base.universal.i18n\
#)

#ifeq ($(PLATFORM),device)
#apps/uart/main_controller.o: SFLAGS += -DHAS_UART=1 -Iion/src/device
#endif

#$(eval $(call depends_on_image,apps/uart/app.cpp,apps/uart/uart_icon.png))
